### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/brick-breaker#4]
### Code
* [x] Proper readable and maintable code with consistent spacing and indentation
* [x] Functions follow the "Do One Thing" rule (single-responsibility)
* [x] Followed DRY (Don’t Repeat Yourself)
* [x] Added comments wherever required
* [x] Proper naming conventions
* [x] Avoided deep nesting

### Readme
* [x] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [x] Setup (Quick start instructions with how to download and use your project)
* [x] Contributing (How can others contribute?)
* [x] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [ ] Wrote tests
* [ ] Deployed the project (if possible)
* [ ] Added CI/CD tools to your project (maybe CircleCI or TravisCI) (if possible)

**Comment by anandbaburajan** [comment]
@SamvruthaShaji and @Aiswarya-anand, great work and thanks for contributing! You're just left with a few items in your TODO! For the Readme, I'd suggest to refer the readme [here](https://github.com/FOSS-Cell-GECPKD/Hide-it). Feel free to let me know at Gitter if you've any doubts! :D
